### PR TITLE
added controls dialog that can be opened with a tickbox or by pressing C

### PR DESCRIPTION
**Pull request by Felipegalind0**
show_ctr_root_painter

### CODE REVIEW

**Comment by Abe404** [comment]
This is awesome! Thanks! Can you add the license and copyright information for the new file? See for example:
https://github.com/Abe404/root_painter/blob/master/painter/src/main/python/assign_corrections.py


Kind regards,
Abraham

**Comment by Abe404** [comment]
Note: This addresses https://github.com/Abe404/root_painter/issues/81

**Comment by Felipegalind0** [comment]
I’m glad you like it, I definitely think it will make it easier for newbies to get started

Copyright notice added per your request

if you’d like me to address another issue please just let me know

**Comment by Abe404** [comment]
Thanks for the swift response. I should have been a bit clearer regarding the copyright notice. I'm doing it on a per file basis (I think that's how it works legally). For this file it is only you who should be listed and the year should be 2024.

""" 
This file is part of the RootPainter.

Copyright (C) 2024 Felipe Galindo

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

"""
[Brief description of what this file does]
"""

# [Your code starts here]

The breif description is entirely optional :) I think the code is short and self explanatory.

**Review by Abe404 — CHANGES_REQUESTED** [review]
Instead of

Copyright (C) 2022 Abraham George Smith
 Copyright (C) 2023 Rohan Howard Orton
 Copyright (C) 202$ Felipe Galindo

The header should just contain 

 Copyright (C) 2024 Felipe Galindo

As this particular file is only authored by you (if I understand correctly).

**Comment by Felipegalind0** [comment]
Oops, my bad, it should be OK now :D

**Review by Abe404 — APPROVED** [review]
Thanks

**Pull request merged**
